### ISSUE TITLE
We should go back to using logging

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen.py#157]
We used to use the standard library's `logging` module, but it felt like overkill, so now we just use print. However, over on Gittip people seem to be inclined to use `logging` (https://github.com/gittip/www.gittip.com/commit/aba52faa, https://github.com/sigmavirus24/www.gittip.com/commit/f4b5bce85f8f6f3b6861d0899dfe7164c1adc6a3), so maybe we should revert to that.

**Comment by techtonik** [comment]
I like Twisted approach to use object that are parsed when needed.
https://twisted.readthedocs.org/en/latest/core/howto/logger.html

I also like to buffer last 100 messages in cyclic memory queue, so that you can dump the log only when you need it with stacktrace.
