### ISSUE TITLE
add high-level noop functions to algorithm

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen.py#424]
Algorithm.py supports [two modification strategies](http://algorithm-py.readthedocs.org/en/latest/#modifying-an-algorithm), a simple one using `insert_before,after` and `remove` methods, and a complex one using `.functions` assignment. For the simple case we should add three noop functions that signal the availability of our main objects: request, resource, and response.

We could talk about an exception hook as well.

**Comment by whit537** [comment]
Raised on the [March 2015 Aspen](https://www.youtube.com/watch?v=xJPfikZXhQ0).

**Comment by whit537** [comment]
Discussing another possible implementation for this on the [April call](https://www.youtube.com/watch?v=fgVeSOUO05Q): implement an algorithm feature where you can populate a list of functions to be run in order whenever a given key becomes available in the state dict.

**Comment by whit537** [comment]
That idea reticketed as https://github.com/gratipay/algorithm.py/issues/8.

**Comment by whit537** [comment]
So then would we reimplement Aspen's algorithm using this feature? What would that look like?

**Comment by pjz** [comment]
To flesh out the spec on this, we need to implement... what? routines named `request_available`, `resource_available`, `response available` ? That would allow for `.insert_before(request_available, my_pre_setup_routine)` which I think reads pretty well.

**Comment by whit537** [comment]
Yes, though in practice I'd expect `.insert_after(request_available, foo)` to be more common.
