### ISSUE TITLE
rename repo to aspen.py

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen.py#485]
Gratipay publishes a number of Python libraries:

 - https://github.com/gratipay/algorithm.py
 - https://github.com/gratipay/dependency_injection.py
 - https://github.com/gratipay/environment.py
 - https://github.com/gratipay/filesystem_tree.py
 - https://github.com/gratipay/postgres.py

Now that Aspen is a library and not an app server, we should rename this repo to `aspen.py` for consistency with our other libraries.

I suppose we may as well rename `aspen-python-plugins` to `aspen.py-plugins`.

And I suppose we may as well rename `aspen-javascript` to `aspen.js` and `aspen-ruby` to `aspen.rb` while we're at it.

Objections, @pjz, et al.?

**Comment by whit537** [comment]
Also:

 - https://github.com/gratipay/simplates.py (forthcoming, #341)

**Comment by pjz** [comment]
aspen-python-plugins is going to be simplate.py-plugins at some point, no point in doing it all twice.

**Comment by whit537** [comment]
"all"?

**Comment by pjz** [comment]
"all" == 'the renaming dance'

**Comment by whit537** [comment]
Well, the only part of the renaming dance affected by #341 is `aspen-python-plugins` -> `_______.py-plugins`, so sure, let's leave that one alone for now. You okay with `aspen.py`, though?

**Comment by pjz** [comment]
For the repo, sure.  Let's keep the pypi project name just 'aspen' though, as the context makes it clear it's python.

**Comment by whit537** [comment]
> For the repo, sure.

Cool.

> Let's keep the pypi project name just 'aspen' though

Agreed. I just double-checked, and that's what we do for the rest of our libraries as well:

 - https://pypi.python.org/pypi/algorithm
 - https://pypi.python.org/pypi/dependency_injection
 - https://pypi.python.org/pypi/environment
 - https://pypi.python.org/pypi/filesystem_tree
 - https://pypi.python.org/pypi/postgres

**Comment by pjz** [comment]
This seems like a bit of yak shaving given outstanding PRs.

**Comment by whit537** [comment]
Perhaps. I got here from https://github.com/gratipay/filesystem_tree.py/pull/9. ;-)

**Comment by whit537** [comment]
Done! :-)

https://github.com/gratipay?query=aspen

**Comment by whit537** [comment]
Python libs: https://github.com/gratipay?query=.py. Satisfying! :-)
