### ISSUE TITLE
hold September 2015 call

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen.py#496]
Back to first Thursday? September 3.

[August](https://github.com/gratipay/aspen-python/issues/474)

**Comment by pjz** [comment]
Sept 3 is fine

**Comment by whit537** [comment]
k

**Comment by pjz** [comment]
I need to push it back an hour until 10am Eastern though, please.

**Comment by whit537** [comment]
Okay.

**Comment by pjz** [comment]
I'm available.

**Comment by whit537** [comment]
https://plus.google.com/hangouts/_/hoaevent/AP36tYc-_RKLKQv-NoT8ItyjuHzPGNwiH2wjOAslwgudydLaNOk1EQ

**Comment by whit537** [comment]
Watch: https://www.youtube.com/watch?v=Z0ILcrZ5uWk.

**Comment by whit537** [comment]
Spelunking Aspen history. Previous repos:

https://www.zetadev.com/svn/public/aspen/trunk/
https://www.zetadev.com/svn/public/httpyd/trunk/

**Comment by whit537** [comment]
!m @pjz
