### ISSUE TITLE
Main pages should contain "report problem" link at the bottom

### ISSUE THREAD

**Issue by techtonik** [gratipay/aspen.py#504]
If #503 is not unique, that means many people have tried it, but nobody bothered enough to report. We need to make it as easy as possible (a very lazy service is a link to GitHub).

**Comment by whit537** [comment]
This will be obsolete once we move the site to RtD (#506).

**Comment by techtonik** [comment]
It is not a good solution. Aspen site is a good concept `learn eating your own dogfood by example` a working site is a nice showcase of its capabilities.

**Comment by whit537** [comment]
Right, that's #505.

**Comment by whit537** [comment]
Closing because our plan is #506. Happy to review a PR for this though. :)
