### ISSUE TITLE
hold October 2015 call

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen.py#507]
October 1 at 9am US/Eastern.

**Comment by whit537** [comment]
[September](https://github.com/gratipay/aspen.py/issues/496)

**Comment by pjz** [comment]
Was this today?

**Comment by whit537** [comment]
@pjz Yeah, I guess so. Wanna try again next week?

**Comment by pjz** [comment]
I guess so. That would be... October 8 at 9am US/Eastern. Talk to you then.

**Comment by pjz** [comment]
Ping?

**Comment by whit537** [comment]
Pong.

**Comment by pjz** [comment]
Link me!

**Comment by whit537** [comment]
https://plus.google.com/hangouts/_/hoaevent/AP36tYdROStjEy_n1lcTLySJiWxLX9n6f7fHaT6MDw0gm_EKvezY4A!

**Comment by whit537** [comment]
https://www.youtube.com/watch?v=awNk2rtaeLI
