### ISSUE TITLE
http://aspen.io/ gives internal error messages

### ISSUE THREAD

**Issue by techtonik** [gratipay/aspen.py#513]
Pretty much every page after the main one is failing.

For example, http://aspen.io/api/website/

**Comment by whit537** [comment]
![screen shot 2015-09-12 at 8 26 10 pm](https://cloud.githubusercontent.com/assets/134455/9834545/8aa9d4a2-598c-11e5-9ef3-87e998594221.png)

**Comment by techtonik** [comment]
Traced to https://github.com/gratipay/aspen.py/issues/297

**Comment by techtonik** [comment]
@whit537 how often is OTP (one time python) vs PPP (per page python) optimization is needed? It is the first time I hear about the difference. Does it worth to maintain a third section with that?

I liked that simplates could be plain .html files. That simplifies transition from pure HTML+JS code and back.

**Comment by techtonik** [comment]
And also, shouldn't you bump major aspen version for that backward-incompatible change?

**Comment by techtonik** [comment]
* [ ] And also, `resources must have at least three pages` is very confusing - `simplates must have at least three sections` - is it what it means?

**Comment by whit537** [comment]
> And also, shouldn't we bump major aspen version for that backward-incompatible change?

No. We're still pre-1.0. See #357 for the definition of 1.0.

**Comment by whit537** [comment]
The fix for this ticket is simple grunt work: we need to add another section separator (`[---]`) to all simplates on the site.

**Comment by techtonik** [comment]
Obligatory sections make simplates less attractive. Is there short explanation why it is not suitable anymore?

**Comment by pjz** [comment]
There's ambiguity if there's only two sections and no template header specified.  We can DWIM if there's a template header (content type and/or renderer) specified, and we should do that - I'll work on a patch for that now, but if we're handed two sections with no template headers, it's unclear if the second page is meant to be python or a template using the default renderer and content type.

**Comment by pjz** [comment]
Fixed with #517

**Comment by whit537** [comment]
Confirmed fixed: http://aspen.io/api/website/.

!m @pjz
