### ISSUE TITLE
looks like `%foo` cannot be used as a path part

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen.py#515]
Test would be:

`%foo.spt`

And:

`http://localhost:8080/%foo`

Then:

`assert request.path['foo'] == `%foo` fails

**Comment by pjz** [comment]
I think you should instead use the URL `http://localhost:8080/%25foo` ; percent is the URL escape character.

**Comment by pjz** [comment]
...and if you *do* use `/%25foo`, you'll find it works fine.  Not a bug.
