### ISSUE TITLE
hold November 2015 call

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen.py#525]
We on for 9am tomorrow, @pjz?

Last month: #507.

**Comment by pjz** [comment]
Yup

**Comment by whit537** [comment]
Cool.

**Comment by whit537** [comment]
@kaguillera and I have started co-working at [Catapult](https://gratipay.com/catapultpgh/) on Thursdays. I'll try to be settled in and ready for the call by 9:00. @pjz I'll try to text you if it looks like I'm running late.

**Comment by whit537** [comment]
Ready, @pjz?

**Comment by pjz** [comment]
yup

**Comment by whit537** [comment]
https://plus.google.com/hangouts/_/hoaevent/AP36tYefV9jN2qu_g3NBMZKhUSSVy4z5AhZFB6F7laCJc7ONrC1A9A

**Comment by whit537** [comment]
Django + Aspen: https://gist.github.com/whit537/1ccf19dc5bd95363564d

**Comment by kaguillera** [comment]
ah I am at catapult now...where are you @whit537 ??

**Comment by whit537** [comment]
@kaguillera In the front conference room! :-)

**Comment by whit537** [comment]
Winding down Aspen in favor of Simplates reticketed as #526.

Also, here's the call archive: https://www.youtube.com/watch?v=oykUQj2MXtI.
