### ISSUE TITLE
hold December 2015 call

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen.py#528]
[November 2015](https://github.com/gratipay/aspen.py/issues/525)

9am EST this Thursday, December 3.

Work for you, @pjz?

**Comment by pjz** [comment]
Yup, I'm here.

**Comment by whit537** [comment]
@pjz Cool, just landed at Catapult, link coming in a minute or two ...

**Comment by whit537** [comment]
Join: https://plus.google.com/hangouts/_/hoaevent/AP36tYfQvGBq2-r2qktgAcqJA8mm0pq_U2VYUtDgOAh7a7rT3sBJkg

Watch: https://www.youtube.com/watch?v=BW4fGCwMzeU

**Comment by pjz** [comment]
I'm there...

**Comment by whit537** [comment]
Or four. :-P

**Comment by whit537** [comment]
Alright, next time I'll have to try harder to book the conference room ahead of time or something. :-)
