### ISSUE TITLE
hold January 2016 call

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen.py#529]
[previous](https://github.com/gratipay/aspen.py/issues/528)

Jan 7

**Comment by whit537** [comment]
@pjz You up for moving the call to the first *Wednesday* of the month instead of Thursday? It would fit my schedule better. Jan 6 work for you?

**Comment by pjz** [comment]
Sorry, I've got plans already this wednesdays, and some standing meetings that make wednesdays busy.  Tuesdays?

**Comment by whit537** [comment]
Sure, let's try Tuesdays. Second Tuesday of the month, I guess? Jan 12 to start?

**Comment by pjz** [comment]
Sounds good.

**Comment by pjz** [comment]
URL me when you're ready

**Comment by whit537** [comment]
join: https://plus.google.com/hangouts/_/hoaevent/AP36tYf3HaSqtDZBJyCUpcZPyZsWNoxqL7vcFLyVXBFxrkqAjqBqjg

watch: https://www.youtube.com/watch?v=_u6SUMPsubQ

**Comment by whit537** [comment]
Aspen history is here: https://github.com/gratipay/aspen.py/issues/526#issuecomment-155439243.

**Comment by whit537** [comment]
Lost you from the call, @pjz. Can you rejoin or is it me?

**Comment by whit537** [comment]
Travis build matrix docs: https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix.
