### ISSUE TITLE
hold February 2016 call

### ISSUE THREAD

**Issue by whit537** [gratipay/aspen.py#537]
[previous](https://github.com/gratipay/aspen.py/issues/529)

Feb 9

**Comment by pjz** [comment]
Ping

**Comment by whit537** [comment]
Pong! Setting it up ...

**Comment by whit537** [comment]
https://plus.google.com/hangouts/_/hoaevent/AP36tYf6HvcHARkTjS1XKaAETyPuc2Be6DLXvcif8ZTXAaTJrX814g

**Comment by whit537** [comment]
View link: https://www.youtube.com/watch?v=k2dHW1EtG8A.

**Comment by whit537** [comment]
cc: @Changaco @jaraco et al.

**Comment by whit537** [comment]
I think we need to do a better job of summarizing our calls, so I took some notes this time, to make it easier to go back and cross-link decision on relevant tickets.
